services:
  db:
    image: postgres:latest
    container_name: qp_db
    environment:
      - POSTGRES_DB=quickpark
      - POSTGRES_USER=parker
      - POSTGRES_PASSWORD=parker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qp_net
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-d", "quickpark", "-U", "parker"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build: ./backend
    container_name: qp_server
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:2564"
    volumes:
      - ./backend:/code/
    ports:
      - "2564:2564"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - qp_net
  
  redis:
    image: redis:latest
    container_name: qp_redis
    ports:
      - "6379:6379"
    networks:
      - qp_net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 3


volumes:
  postgres_data:

networks:
  qp_net:
